# .github/workflows/ct.yml
name: CT - Continuous Testing

on:
  workflow_run:
    workflows: ["CD - Deploy"]
    types:
      - completed

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run integration tests
        run: |
          pip install pytest requests
          pytest --maxfail=1 --disable-warnings -q
